[platformio]
default_envs = bluepill_f103c6_serial

[env]
platform = ststm32
board = bluepill_f103c6
framework = arduino
monitor_speed = 1000000
build_src_filter = +<main.cpp>

[env:bluepill_f103c6_stlink]
upload_protocol = stlink

[env:bluepill_f103c6_serial]
upload_protocol = serial
upload_port = COM12
upload_speed = 57600
